# Generated by Django 4.1.1 on 2023-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
