# Generated by Django 4.1.1 on 2023-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
