# Generated by Django 4.1.1 on 2023-02-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_alter_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
