# Generated by Django 4.1.1 on 2023-02-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='On the way', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
