# Generated by Django 4.1.1 on 2023-02-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_order_orderstatus_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderstatus',
            new_name='order_status',
        ),
    ]
