# Generated by Django 4.1.1 on 2023-02-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
