# Generated by Django 4.1.1 on 2023-02-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0020_alter_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
