# Generated by Django 4.1.1 on 2023-02-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0021_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
