# Generated by Django 4.1.1 on 2023-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0022_alter_order_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
    ]
