# Generated by Django 4.1.1 on 2023-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0023_alter_order_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(upload_to='photos/orderimg'),
        ),
    ]
