# Generated by Django 4.1.1 on 2023-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0030_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
