# Generated by Django 4.1.1 on 2023-02-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0032_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
