# Generated by Django 4.1.1 on 2023-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0033_orderitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
