# Generated by Django 4.1.1 on 2023-03-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0038_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(upload_to='photos/image'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
