# Generated by Django 4.1.1 on 2023-03-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0040_alter_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(upload_to='order/photos'),
        ),
    ]
