# Generated by Django 4.1.1 on 2023-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0048_product_average_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
