# Generated by Django 4.1.1 on 2023-03-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0050_remove_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
    ]
